import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from '../auth';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="border-b-2 border-slate-300 p-4 bg-slate-200">
          <div className="text-right">
            { session?.user &&
              <span className="p-2">{ session.user.email }</span>
            }
            <a href="/api/auth/signout" className="p-2 m-2 border border-blue-700 rounded bg-blue-600 text-slate-200 hover:text-white">Sign out</a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
