name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run node tests
        run: npm run full:test
      - name: Upload test report
        if: failure() # && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
